# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text="This should be an absolute path, excluding the domain name. Example: '/events/search/'.", max_length=255, verbose_name='Redirect from')),
                ('new_path', models.CharField(blank=True, help_text="This can be either an absolute path (as above) or a full URL starting with 'http://'.", max_length=255, verbose_name='Redirect to')),
                ('response_code', models.CharField(choices=[('301', '301'), ('302', '302')], default='301', help_text='This is the http response code returned if a destination is specified. If no destination is specified the response code will be 410.', max_length=3)),
                ('active', models.BooleanField(default=True, help_text='You can untick this option if you want to create a redirect, but not use it immediately.')),
                ('tags', models.CharField(blank=True, help_text="A comma-separated list of tags. <br /><b>Note:</b> Press 'tab' after entering each tag.", max_length=255)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
