# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-02 15:37
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsredirect',
            options={'ordering': ('old_path',), 'verbose_name': 'CMS Redirect', 'verbose_name_plural': 'CMS Redirects'},
        ),
        migrations.AlterField(
            model_name='cmsredirect',
            name='new_path',
            field=models.CharField(blank=True, help_text="This can be either an absolute path (as above) or a full URL starting with 'http://'.", max_length=255, verbose_name='redirect to'),
        ),
        migrations.AlterField(
            model_name='cmsredirect',
            name='old_path',
            field=models.CharField(db_index=True, help_text="This should be an absolute path, excluding the domain name. Example: '/events/search/'.", max_length=255, verbose_name='redirect from'),
        ),
        migrations.AlterField(
            model_name='cmsredirect',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='A link to a page has priority over a text link.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='cmsredirect',
            name='response_code',
            field=models.CharField(choices=[('301', '301'), ('302', '302')], default='301', help_text='This is the http response code returned if a destination is specified. If no destination is specified the response code will be 410.', max_length=3, verbose_name='response code'),
        ),
        migrations.RemoveField(
            model_name='cmsredirect',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cmsredirect',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='cmsredirect',
            unique_together=set([('site', 'old_path')]),
        ),
    ]
